language: erlang

env:
  - LUA="luajit-2.0.0-beta9"

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq git luajit luarocks libev-dev make
  - sudo ln -s /usr/bin/luajit-2.0.0-beta9 /usr/bin/luajit
  - sudo luarocks install luafilesystem
  - sudo luarocks install copas
  - sudo luarocks install moonscript
  - sudo luarocks install lua-ev
  - git clone git://github.com/Olivine-Labs/say.git
  - cd say
  - sudo luarocks make
  - cd ../
  - git clone git://github.com/Olivine-Labs/luassert.git
  - cd luassert
  - sudo luarocks make
  - cd ../

script: "sudo luarocks make && sudo busted"

notifications:
  webhooks:
    - http://exobot.herokuapp.com/hubot/travis
  recipients:
    - engineers@olivinelabs.com
  email:
    on_success: always
    on_failure: always
